// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"eMobile/internal/api"
	"eMobile/internal/config"
	"eMobile/internal/db"
	"eMobile/internal/domain/providers/song"
	"log/slog"
)

// Injectors from wire.go:

func InitializeAPI(cfg *config.Config, log *slog.Logger) (*api.ServerHTTP, error) {
	sqlDB, err := db.ConnectToBD(cfg)
	if err != nil {
		return nil, err
	}
	repo := song.ProvideSongRepository(sqlDB)
	service := song.ProvideSongService(repo)
	handler := song.ProvideSongHandler(service, log)
	serverHTTP := api.NewServerHTTP(cfg, handler)
	return serverHTTP, nil
}
