definitions:
  ResponseError:
    properties:
      error:
        type: string
    type: object
  eMobile_internal_domain_models_song.Create:
    properties:
      group:
        type: string
      name:
        type: string
    required:
    - group
    - name
    type: object
  eMobile_internal_domain_models_song.Song:
    properties:
      group:
        type: string
      link:
        type: string
      name:
        type: string
      releaseDate:
        type: string
      text:
        type: string
    required:
    - group
    - name
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /song:
    post:
      consumes:
      - application/json
      description: Create a new song in the system
      parameters:
      - description: Song data
        in: body
        name: song
        required: true
        schema:
          $ref: '#/definitions/eMobile_internal_domain_models_song.Create'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/eMobile_internal_domain_models_song.Song'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ResponseError'
      summary: Create a new song
      tags:
      - songs
  /song/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a song from the system by its ID
      parameters:
      - description: Song ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ResponseError'
      summary: Delete a song by ID
      tags:
      - songs
    put:
      consumes:
      - application/json
      description: Update an existing song in the system by its ID
      parameters:
      - description: Song ID
        in: path
        name: id
        required: true
        type: integer
      - description: Updated song data
        in: body
        name: song
        required: true
        schema:
          $ref: '#/definitions/eMobile_internal_domain_models_song.Song'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/eMobile_internal_domain_models_song.Song'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ResponseError'
      summary: Update a song by ID
      tags:
      - songs
swagger: "2.0"
